### ISSUE TITLE
Error while creating plots

### ISSUE THREAD

**Issue by simaju** [Cibiv/BODscore#1]
The plot_coverage_sqlite.py script created plots for all SNPs in chromosome 1, but after plotting coverage for the last SNP in chromosome 1, I got the following error:

```
Traceback (most recent call last):
  File "../Tools/BODscore/src/pyscripts/plot_coverage_sqlite.py", line 107, in <module>
    curs.execute("SELECT Count(*) FROM " + table_base + condition)
sqlite3.OperationalError: near "WHERE": syntax error
```

I used the following command:

```
python3 ../Tools/BODscore/src/pyscripts/plot_coverage_sqlite.py 29025_BODscore.db -t testsample -o ./plots
```

Thanks,
Sini

**Comment by DSLituiev** [comment]
Can you please submit the log before the error (at least last 10 rows)?

**Comment by DSLituiev** [comment]
If you could also provide your test files (email or dropbox), I can try them.
